/*Localizando objetos pelo nome.
  Exceto INDEX, SEQUENCE, SYNONYM*/
  
SELECT O.OWNER, O.OBJECT_NAME, O.OBJECT_TYPE, O.STATUS
FROM   ALL_OBJECTS O
WHERE  O.OWNER = USER
AND    O.OBJECT_TYPE NOT IN ('INDEX', 'SEQUENCE', 'SYNONYM')
AND    O.OBJECT_NAME LIKE UPPER('%&NOME_OBJETO%')
ORDER BY O.OBJECT_NAME, O.OBJECT_TYPE;