gbh=groupByHaving
le=logExecucao
toda=toDate('','DD/MM/YYYY')
toda24=toDate('','dd/mm/yyyy hh24:mi:ss')
analisebeneficiario=analiseBeneficiario
fil=For In Loop
scrp=padrão para envio de scripts
ift=if then end if;
ifte=if then else end if;
findtable=Localiza tabelas que possua uma determinada coluna
findobj=Localiza objetos pelo nome
findcontent=Localiza objetos pelo seu conteúdo